---
# Source: cluster-api-aws/templates/aws-cluster.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: c27f6qjma
  namespace: c27f6qjma
spec:
  region: ap-northeast-2
  sshKeyName: tks-seoul
  bastion:
    enabled: false
